WIP/User/TamNV/iVolunteer/iVolunteer/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Transactions;
using System.Web.Mvc;
using iVolunteer.Models.Data_Definition_Class.MongoDB.CollectionClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.InformationClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ItemClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.LinkClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.SDClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.StructureClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ListClass;
using iVolunteer.Models.Data_Definition_Class.SQL;
using iVolunteer.Models.Data_Access_Object.MongoDB;
using iVolunteer.Models.Data_Access_Object.SQL;
using iVolunteer.Common;
using MongoDB.Bson;

namespace iVolunteer.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Get group list
        /// </summary>
        /// <param name="skip"></param>
        /// <param name="number"></param>
        /// <returns></returns>
        public ActionResult ListGroup(int skip = 0, int number = 5)
        {
            //check input, use default value if not pass
            if (skip < 0||number <=0)
            {
                skip = 0;
                number = 5;
            }

            Mongo_Group_DAO groupDAO = new Mongo_Group_DAO();
            var result = groupDAO.Get_All_GroupInformation(skip, number);
            return View(result);
        }

        public ActionResult ListProject(int skip = 0, int number = 5)
        {
            //check input, use default value if not pass
            if (skip < 0 || number <= 0)
            {
                skip = 0;
                number = 5;
            }

            Mongo_Project_DAO projectDAO = new Mongo_Project_DAO();
            var result = projectDAO.Get_All_ProjectInformation(skip, number);
            return View(result);
        }

        public ActionResult ListUser(int skip = 0, int number = 5)
        {
            //check input, use default value if not pass
            if (skip < 0 || number <= 0)
            {
                skip = 0;
                number = 5;
            }

            Mongo_User_DAO projectDAO = new Mongo_User_DAO();
            var result = projectDAO.Get_All_UserInformations(skip, number);
            return View(result);
        }
    }
}

WIP/User/TamNV/iVolunteer/iVolunteer/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Transactions;
using System.Web.Mvc;
using iVolunteer.Models.Data_Definition_Class.MongoDB.CollectionClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.InformationClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ItemClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.LinkClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.SDClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.StructureClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ListClass;
using iVolunteer.Models.Data_Definition_Class.SQL;
using iVolunteer.Models.Data_Access_Object.MongoDB;
using iVolunteer.Models.Data_Access_Object.SQL;
using iVolunteer.Common;
using MongoDB.Bson;

namespace iVolunteer.Controllers
{
    public class GroupController : Controller
    {
        // GET: Group
        public ActionResult Index()
        {
            return View();
        }
        // GET : CreateGroup
        [HttpGet]
        public ActionResult CreateGroup()
        {
            return View();
        }

        public ActionResult CreateGroup(GroupInformation groupInfo)
        {
            ///
            /// This would be check permission and validate data, will add later
            ///

            
            //set missing information
            groupInfo.DateCreate = DateTime.Now;
            groupInfo.MemberCount = 1;
            groupInfo.AvtImgLink = Constant.DEFAULT_AVATAR;
            groupInfo.CoverImgLink = Constant.DEFAULT_COVER;
            groupInfo.IsActivate = true;

            //craete creator
            UserSD creator = new UserSD();
            creator.UserID = Session["UserID"].ToString();
            creator.DisplayName = Session["DisplayName"].ToString();
            creator.AvtImgLink = Session["Avatar"].ToString();

            //create mongo Group
            Mongo_Group mongo_Group = new Mongo_Group(creator,groupInfo);

            //create sql Group
            SQL_Group sql_Group = new SQL_Group();
            sql_Group.GroupID = mongo_Group._id.ToString();
            sql_Group.IsActivate = true;

            // create first relation
            SQL_User_Group relation = new SQL_User_Group();
            relation.UserID = creator.UserID ;
            relation.GroupID = mongo_Group._id.ToString();
            relation.RelationType = Constant.DIRECT_RELATION;

            //this code will change user information, will add later

            //start transaction
            
            using (var transaction = new TransactionScope())
            {
                try
                {
                    // create DAO instance
                    Mongo_Group_DAO mongo_Group_DAO = new Mongo_Group_DAO();
                    SQL_Group_DAO sql_Group_DAO = new SQL_Group_DAO();
                    SQL_User_Group_DAO sql_User_Group_DAO = new SQL_User_Group_DAO();

                    //write to DB
                    mongo_Group_DAO.Add_Group(mongo_Group);
                    sql_Group_DAO.Add_Group(sql_Group);
                    sql_User_Group_DAO.Add_Relation(relation);
                    transaction.Complete();
                }
                catch
                {
                    transaction.Dispose();
                    ViewBag.Message = "Có lỗi xảy ra, vui lòng thử lại sau ít phút";
                    return View();
                }
            }
            ViewBag.Message = "Tạo nhóm tình nguyện thành công";
            return RedirectToAction("Newfeed","Home");
        }

        public ActionResult GroupInformation(string groupID)
        {
            Mongo_Group_DAO groupDAO = new Mongo_Group_DAO();
            var result = groupDAO.Get_GroupInformation(groupID);
            return View(result);
        }
    }
}

WIP/User/TamNV/iVolunteer/iVolunteer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Transactions;
using System.Web.Mvc;
using iVolunteer.Models.Data_Definition_Class.MongoDB.CollectionClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.InformationClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ItemClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.LinkClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.SDClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.StructureClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ListClass;
using iVolunteer.Models.Data_Definition_Class.SQL;
using iVolunteer.Models.Data_Access_Object.MongoDB;
using iVolunteer.Models.Data_Access_Object.SQL;
using iVolunteer.Common;
using MongoDB.Bson;
using iVolunteer.Models.Data_Definition_Class.ViewModel;

namespace iVolunteer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult FrontPage()
        {
            return View();
        }
        public ActionResult Newfeed()
        {
            if (Session["UserID"] == null) return RedirectToAction("Login");
            return View("Newfeed");
        }

        // GET: Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel loginModel)
        {
            SQL_Account_DAO accountDAO = new SQL_Account_DAO();
            SQL_Account account = new SQL_Account();
            try
            {
                account = accountDAO.Get_Account_By_Email(loginModel.Email);
            }
            catch
            {
                account = null;
            }

            if (account == null)
            {
                ViewBag.Message = "Tài khoản không tồn tại";
                return View("Login", loginModel);
            }
            if (!account.IsActivate)
            {
                ViewBag.Message = "Tài khoản đã bị khóa";
                return View("Login", loginModel);
            }
            if (!account.IsConfirm)
            {
                ViewBag.Message = "Tài khoản chưa được xác nhận";
                return View("Login", loginModel);
            }
            if (account.Password != loginModel.Password)
            {
                ViewBag.Message = "Mật khẩu không chính xác";
                return View("Login", loginModel);
            }
            // code save cookie wil be added here later


            Session["UserID"] = account.UserID;
            Session["DisplayName"] = account.DisplayName;
            Session["Avatar"] = account.AvtImgLink;
            Session["IsAdmin"] = account.IsAdmin;
            
            return RedirectToAction("Newfeed");
        }
        //GET : Register
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterModel registerModel)
        {
            Mongo_User_DAO mongo_User_DAO = new Mongo_User_DAO();
            SQL_Account_DAO sql_Account_DAO = new SQL_Account_DAO();
            string err = "";
            bool isValid = true;
            // validate information
            if (!ValidationHelper.IsValidEmail(registerModel.Email) 
                    || !ValidationHelper.IsValidIdentifyID(registerModel.IdentifyID)
                    || !ValidationHelper.IsValidPassword(registerModel.Password)
                    || !ValidationHelper.IsValidPhone(registerModel.Phone))
            {
                err = "Thông tin không hợp lệ" + Environment.NewLine;
                isValid = false;
            }

            // check if email existed
            if (sql_Account_DAO.Is_Email_Exist(registerModel.Email))
            {
                err = err + "Email đã được đăng ký" + Environment.NewLine;
                isValid = false;
            }

            // check if identifyID exist
            if (sql_Account_DAO.Is_IdentifyID_Exist(registerModel.IdentifyID))
            {
                err = err + "Số chứng minh nhân dân này đã được đăng ký" + Environment.NewLine;
                isValid = false;
            }
            if (!isValid)
            {
                ViewBag.Message = err;
                return View(registerModel);
            }
            //create account in SQL
            ObjectId _id = ObjectId.GenerateNewId();
            SQL_Account account = new SQL_Account();
            account.UserID = _id.ToString();
            account.Email = registerModel.Email;
            account.Password = registerModel.Password;
            account.IndentifyID = registerModel.IdentifyID;
            account.DisplayName = registerModel.RealName;
            account.AvtImgLink = Constant.DEFAULT_AVATAR;
            account.IsAdmin = Constant.IS_USER;
            account.IsActivate = Constant.IS_ACTIVATE;
            account.IsConfirm = Constant.IS_NOT_CONFIRMED;

            //create account in MongoDB
            Mongo_User user = new Mongo_User(registerModel);
            //write to DB
            
            using (TransactionScope transaction = new TransactionScope())
            {
                try
                {
                    //create DAO instance
                    //write to DB
                    mongo_User_DAO.Add_User(user);
                    sql_Account_DAO.Add_Account(account);

                    transaction.Complete();
                }
                catch
                {
                    transaction.Dispose();
                    ViewBag.Message = "Có lỗi xảy ra, vui lòng thử lại sau ít phút";
                    return View();
                }
            }
            return RedirectToAction("Login");
        }
    }
}

WIP/User/TamNV/iVolunteer/iVolunteer/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Transactions;
using System.Web.Mvc;
using iVolunteer.Models.Data_Definition_Class.MongoDB.CollectionClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.InformationClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ItemClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.LinkClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.SDClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.StructureClass;
using iVolunteer.Models.Data_Definition_Class.MongoDB.EmbeddedClass.ListClass;
using iVolunteer.Models.Data_Definition_Class.SQL;
using iVolunteer.Models.Data_Access_Object.MongoDB;
using iVolunteer.Models.Data_Access_Object.SQL;
using iVolunteer.Common;
using MongoDB.Bson;

namespace iVolunteer.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {
            return RedirectToAction("CreateProject");
        }
        //GET : CreateProject
        [HttpGet]
        public ActionResult CreateProject()
        {
            return View();
        }
        //POST : CreateProject
        [HttpPost]
        public ActionResult CreateProject( ProjectInformation projectInfo )
        {
            ///
            /// This would be check permission and validate data, will add later
            ///

            //set missing information for project
            projectInfo.DateCreate = DateTime.Now;
            projectInfo.MemberCount = 1;
            projectInfo.AvtImgLink = Constant.DEFAULT_AVATAR;
            projectInfo.CoverImgLink = Constant.DEFAULT_COVER;
            projectInfo.IsActivate = true;
            projectInfo.IsRecruit = true;

            //create creator
            UserSD creator = new UserSD();
            creator.UserID = Session["UserID"].ToString();
            creator.DisplayName = Session["DisplayName"].ToString();
            creator.AvtImgLink = Session["Avatar"].ToString();

            //create mongo project
            Mongo_Project mongo_Project = new Mongo_Project(creator, projectInfo);

            //create sql project
            SQL_Project sql_Project = new SQL_Project();
            sql_Project.ProjectID = mongo_Project._id.ToString();
            sql_Project.IsActivate = true;

            //create first relation
            SQL_User_Project relation = new SQL_User_Project();
            relation.UserID = creator.UserID;
            relation.ProjectID = mongo_Project._id.ToString();
            relation.RelationType = Constant.DIRECT_RELATION;

            //start transaction
            using (var transaction = new TransactionScope())
            {
                try
                {
                    //create DAO instance 
                    Mongo_Project_DAO mongo_Project_DAO = new Mongo_Project_DAO();
                    SQL_Project_DAO sql_Project_DAO = new SQL_Project_DAO();
                    SQL_User_Project_DAO sql_User_Project_DAO = new SQL_User_Project_DAO();
                    //write to DB
                    mongo_Project_DAO.Add_Project(mongo_Project);
                    sql_Project_DAO.Add_Project(sql_Project);
                    sql_User_Project_DAO.Add_Relation(relation);

                    transaction.Complete();
                }
                catch
                {
                    transaction.Dispose();
                    ViewBag.Message = "Có lỗi xảy ra, vui lòng thử lại sau ít phút";
                    return View();
                }
            }
            ViewBag.Message = "Tạo dự án tình nguyện thành công";
            return RedirectToAction("Newfeed", "Home");
        }
    }
}

WIP/User/TamNV/iVolunteer/iVolunteer/Views/Home/Login.cshtml
@model iVolunteer.Models.Data_Definition_Class.ViewModel.LoginModel

@Html.AntiForgeryToken()
<div id="loginForm" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-content">
        <div class="modal-body">
            <div class="row">

                <!-- Register -->
                <div class="col-sm-6 col-xs-6">
                    <div class="row">
                        <h3 style="text-align: center; font-weight: bold; color: #049f88;">Tôi là người dùng mới</h3>
                    </div>
                    <div class="row" style="line-height: 250px; text-align: center">
                        <div class="col-xs-12 login-register-label">
                            <label>Đăng kí ngay</label>
                            <a href="@Url.Action("Register","Home")"><i class="material-icons md-mygreen md-48">play_arrow</i></a>
                        </div>
                    </div>
                </div>

                <div class="divider-vertical-login"></div>
                @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { id = "formValidation" }))
                {
                    <!-- Login -->
                    <div class="col-sm-5 col-xs-5">
                        <div class="row">
                            <h3 style="text-align: center; font-weight: bold; color: #049f88">Đăng nhập</h3>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12">
                                <form role="form" class="login-form">
                                    <div class="row">
                                        <div class="col-xs-4 login-label">
                                            @Html.LabelFor(model => model.Email, htmlAttributes: new
                                       { @*@class = "control-label col-md-2"*@ })
                                            @*<label for="email">Email:</label>*@
                                        </div>
                                        <div class="col-xs-8 text-input">
                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập Email", @id = "email", @name = "txtEmail" } })
                                            @*<input type="text" name="txtEmail" class="form-control" id="email" placeholder="Nhập Email ...">*@
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-4 login-label">
                                            @Html.LabelFor(model => model.Password, htmlAttributes: new { })
                                            @*<label for="password">Mật khẩu:</label>*@
                                        </div>
                                        <div class="col-xs-8 text-input">
                                            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập mật khẩu", @id = "password" }, type = "password" })
                                            @*<input type="text" name="txtPass" class="form-control" id="password" placeholder="Nhập mật khẩu ...">*@
                                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-8 col-xs-offset-4">
                                            <div class="checkbox">
                                                <label>
                                                    @Html.EditorFor(model => model.IsRemember)
                                                    @Html.LabelFor(model => model.IsRemember, htmlAttributes: new
                                               { @*@class = "control-label col-md-2"*@ })
                                                    @*<input type="checkbox"> Ghi nhớ đăng nhập*@

                                                    @Html.ValidationMessageFor(model => model.IsRemember, "", new { @class = "text-danger" })


                                                </label>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-8 col-xs-offset-4 text-input">
                                            <button class="btn btn-login" type="submit" id="login">ĐĂNG NHẬP</button>
                                        </div>
                                    </div>
                                    <div>
                                        @ViewBag.Message
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-11 col-xs-offset-1" style="margin-top: 20px">
                                <a href="@Url.Action("ForgotPassword", "Account")">Quên mật khẩu?</a>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>

    </div>
</div>

WIP/User/TamNV/iVolunteer/iVolunteer/Views/Home/Newfeed.cshtml
<div class="row">
    <div class="col-md-3">
        @Html.Partial("_LeftSideBar")
    </div>
    <div class="col-md-9">
        <div class="card-panel">
            <div class="row">
                <div class="col-sm-7 col-md-7">
                    <!-- Post Owner -->
                    <table class="table-post-ava">
                        <tr>
                            <td rowspan="2"><object type="image/svg+xml" data="images/avatar.svg" width="40" height="40" border="1"></object></td>
                            <td class="td">
                                <a href="" class="user-name">Võ Tôn Phúc</a>
                                <i class="glyphicon glyphicon-triangle-right" style="font-size: smaller"></i>
                                <a href="project.html" class="user-name">Tôi Tình Nguyện</a>
                            </td>
                        </tr>
                        <tr>
                            <td class="td" style="color: gray; font-size:90%">16 minutes</td>
                        </tr>
                    </table>
                </div>
                <!-- Navigation button -->
                <div class="col-sm-5 col-md-5" style="text-align: right;">
                    <button class="btn btn-image" type="submit" data-toggle="tooltip" title="Xóa"><i class="glyphicon glyphicon-trash"></i></button>
                    <button class="btn btn-image" type="submit" data-toggle="tooltip" title="Thu gọn"><i class="glyphicon glyphicon-menu-right"></i></button>
                </div>
            </div>
            <!-- Post Content -->
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="card-content">
                        <p>Hiện tại nhóm mình vẫn đang tổ chức Project Toa Tàu Trẻ Em. Tuy nhiên mình muốn mọi người nghĩ dần idea cho hoạt động sắp tới sau khi Toa Tàu Trẻ Em kết thúc. Mọi người cố gắng nghĩ ra các ý tưởng trong tuần này, cuối tuần chung ta sẽ vote ý tưởng và bắt đầu xây plan các kiểu cho dự án sắp tới của bọn mình luôn nhé.<br>Cám ơn mọi người nhiều. :))) </p>
                    </div>
                </div>
            </div>
            <div class="divider-holizon"></div>
            <!-- Interaction Panel -->
            <div class="row">
                <!-- Interaction Button -->
                <div class="col-md-6 col-sm-6">
                    <button type="button" class="btn-card" aria-label="Left Align">
                        <span class="glyphicon glyphicon-heart-empty"></span>
                        Like
                    </button>
                    <button type="button" class="btn-card" aria-label="Left Align">
                        <span class="glyphicon glyphicon-comment"></span>
                        Comment
                    </button>
                </div>

                <!-- Interaction Counter -->
                <div class="col-md-6 col-sm-6" style="text-align: right">
                    <div class="row">
                        <ul class="list-interaction">
                            <li>
                                <i class="glyphicon glyphicon-heart"></i>
                                <span><strong>15</strong></span>
                            </li>
                            <li>
                                <i class="glyphicon glyphicon-comment"></i>
                                <span><strong>2</strong></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="divider-holizon"></div>
            <!-- Comment -->
            <div class="row">
                <div class="col-md-1 col-sm-1">
                    <object type="image/svg+xml" data="images/avatar.svg" width="40" height="40" border="1"></object>
                </div>

                <div class="col-md-9 col-sm-9">
                    <div class="row">
                        <a href="" class="user-name">Đặng Thị Bình</a>
                        <span>&bull; 5 phút trước</span>
                    </div>
                    <div class="row">
                        <p>Mình thấy dạy tiếng anh cho mấy đứa nhỏ ở Tân Xã cũng hợp lí...</p>
                    </div>
                </div>
            </div>
            <!-- Comment -->
            <div class="row">
                <div class="col-md-1 col-sm-1">
                    <object type="image/svg+xml" data="images/avatar.svg" width="40" height="40" border="1"></object>
                </div>

                <div class="col-md-9 col-sm-9">
                    <div class="row">
                        <a href="" style="color: #049f88; font-weight: bold">Nguyễn Bá Long</a>
                        <span>&bull; 2 phút trước</span>
                    </div>
                    <div class="row">
                        <p>Cũng được đấy nhỉ :))).</p>
                    </div>
                    <div class="row">
                        <div></div>
                    </div>
                </div>
            </div>
            
        </div>

    </div>
</div>


@*<div>
    @Html.ActionLink("Tạo nhóm tình nguyện", "CreateGroup", "Group")
</div>
<div>
    @Html.ActionLink("Tạo dự án tình nguyện", "CreateProject", "Project")
</div>
<div>
    @Html.ActionLink("Danh sách các nhóm tình nguyện", "ListGroup", "Admin", new { skip = 0, number = 5 },null)
</div>*@
@*<div>
    @Html.ActionLink("Danh sách các dự án tình nguyện", "ListProject", "Admin", new { skip = 0, number = 5 },null)
</div>*@
@*<div>
    @Html.ActionLink("Danh sách người dùng", "ListUser", "Admin", new { skip = 0, number = 5 }, null)
</div>
<div>
    @Html.ActionLink("Thông tin của tôi", "UserInformationDetail", "User", new { userID = Session["UserID"].ToString() },null)
</div>*@